- 난수

In [4]:
# 기본: 0부터 1사이 실수값 생성
# 보통 프로그래밍 언어를 통한 난수는 난수값이 설정
# 조금 더 난수를 만들고 싶으면 난수값을 정하는 씨앗값을 그때그때 바꾸는 형태로 사용

In [5]:
import numpy as np

In [6]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [8]:
np.random.rand(5)

array([0.60276338, 0.54488318, 0.4236548 , 0.64589411, 0.43758721])

In [16]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [20]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [21]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [22]:
for i in range(10):
    print(np.random.rand())

0.08712929970154071
0.02021839744032572
0.832619845547938
0.7781567509498505
0.8700121482468192
0.978618342232764
0.7991585642167236
0.46147936225293185
0.7805291762864555
0.11827442586893322


In [23]:
x = np.arange(10); x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# shuffle
np.random.shuffle(x)

print(x)

[3 6 4 5 2 9 7 8 1 0]


In [25]:
# 데이터 샘플링: 이미 있는 데이터 집합에서 무작위로 랜덤하게 선택하는 것
# np.random.choice(원본 데이터, size, replace = True/False, p)
# - 원본데이터: 데이터 집합, 숫자로 적으면 range(x)로 인식
# - size: 샘플 숫자
# - replace: True(복원 추출 - 한 번 선택한 데이터를 다시 선택 가능), False(비복원 추출)
# - p: 각 데이터가 선택될 수 있는 확률, 생략하면 다 동일한 확률

In [35]:
x = np.random.choice(5,5,replace = False); x

array([3, 1, 0, 2, 4])

In [36]:
x = np.random.choice(5,3,replace = False); x

array([1, 2, 0])

In [39]:
x = np.random.choice(5,10,replace = False); x # 비복원 추출인데 원본 데이터가 5개인데 10개의 데이터를 선택하라고 해서 에러

ValueError: Cannot take a larger sample than population when 'replace=False'

In [42]:
x = np.random.choice(5,10,replace = True); x # 복원 추출로 하니까 노상관이지?

array([0, 1, 2, 4, 2, 0, 3, 2, 2, 0])

In [43]:
x = np.random.choice(5,10,replace = True, p = [0.1, 0, 0, 0.3, 0.6]); x # p: 요소별 선택될 확률을 지정

array([4, 4, 0, 3, 3, 3, 3, 3, 4, 0])

In [45]:
# 난수 생성 함수
# rand(): 0 ~ 1 사이 실수   - 균일분포
#    -rand(
# randn(): 실수   - 가우시안 표준 정규 분포
# randint(): 정수   - 균일분포의 정수 난수
#    - randint(low, high, size)


In [46]:
np.random.rand(5)

array([0.69247212, 0.56660145, 0.26538949, 0.52324805, 0.09394051])

In [49]:
np.random.randn(10)

array([-0.40317695,  1.22244507,  0.20827498,  0.97663904,  0.3563664 ,
        0.70657317,  0.01050002,  1.78587049,  0.12691209,  0.40198936])

In [57]:
np.random.randn(3, 5) # 3행 5열짜리

array([[ 0.68159452,  0.40318568, -0.68405925,  1.26232219, -2.00555659],
       [-0.3320304 , -0.2961004 , -2.21836076, -0.18350288,  0.39230806],
       [ 0.24163481,  0.10393591, -0.82957119,  0.49275939,  0.09011279]])

In [70]:
# [실습] 로또번호 5천원어치 구해보세요.
# 로또번호: 1부터 45까지 숫자 중 6개가 랜덤하게 추출
np.random.randint(1, 46, [5, 6]) # 자동으로 행마다 복원 추출

array([[17, 43, 29, 27, 24,  3],
       [39, 10,  3, 45, 42, 26],
       [37, 27,  5, 42, 11, 13],
       [41, 34, 38, 40, 33, 34],
       [27, 36, 26, 25, 19, 21]])

In [98]:
# sort - 매우 중요!!!! 기본: 행 단위로 정렬
a = np. array([[3, 4, 5, 6],
               [4, 6, 8, 2],
               [4, 7, 9, 1]])
np.sort(a)

array([[3, 4, 5, 6],
       [2, 4, 6, 8],
       [1, 4, 7, 9]])

In [94]:
b = np.array([1,3,4,6,8,9,4,4,4,7,9,9])

np.sort(b); b

array([1, 3, 4, 6, 8, 9, 4, 4, 4, 7, 9, 9])

In [95]:
a = a.reshape(-1)
np.sort(a).reshape(3,4)

array([[1, 2, 3, 4],
       [4, 4, 5, 6],
       [6, 7, 8, 9]])

In [100]:
np.sort(a, axis = 0) # 열 단위로 정렬 -> 이거 무슨 기준이지

array([[3, 4, 5, 1],
       [4, 6, 8, 2],
       [4, 7, 9, 6]])

In [102]:
# 전체 정렬: rank2을 rank1로 바꾼 다음 정렬 수행 -> rank2로 배열
np.sort(a.flatten()).reshape(a.shape)

array([[1, 2, 3, 4],
       [4, 4, 5, 6],
       [6, 7, 8, 9]])

In [103]:
x = np.arange(9); x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
# split: 배열 나누기(쪼개기), 각 값을 지정한 숫자로 등분해서 새로운 배열로 리턴
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [106]:
y = np.split(x, 3); y

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [108]:
print(y[0], ":",y[1],":",y[2])

[0 1 2] : [3 4 5] : [6 7 8]


In [109]:
# 등분할 숫자를 개수가 아닌 원본 배열의 인덱스 번호로 지정 가능
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
x2 = np.split(x,[3]); x2

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8])]

In [111]:
# 인덱스 번호 여러 개 지정 가능
x3 = np.split(x, [2, 5, 7]); x3

[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8])]

In [115]:
x4 = np.split(x, [2, 5, 7, 10]); x4 # 없는 인덱스 번호가 있어도 에러가 발생하지 않는다. (pass 처리)

[array([0, 1]),
 array([2, 3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([], dtype=int32)]

In [125]:
# dsplit(): 다른 깊이를 같은 열 기준으로 나눠서 묶기
# dsplit(depth(깊이), axis(축))
y = np.arange(16).reshape(2, 2, 4);  print(y)
print('-' * 30)
print(y.ndim, y.shape)
print('-' * 30)
print(np.dsplit(y, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
------------------------------
3 (2, 2, 4)
------------------------------
[array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]]]), array([[[ 2,  3],
        [ 6,  7]],

       [[10, 11],
        [14, 15]]])]


In [127]:
# hsplit(): 다른 깊이를 같은 행 기준으로 같이 나눠서 묶기
y2 = np.hsplit(y, 2); y2

[array([[[ 0,  1,  2,  3]],
 
        [[ 8,  9, 10, 11]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[12, 13, 14, 15]]])]

In [130]:
# 요소에 대한 추가/ 삭제
arr = np.array([[1,2,3,4], 
                [5,6,7,8],
                [9,10,11,12]]); arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
# 삭제: np.delete(원데이터, index, axis)
arr1 = np.delete(arr, 1); arr1 # axis를 지정하지 않으면 모든 요소 지정함에 유의 + 공간이 null이 된 게 아니라 자체가 사라짐
## why?? delete 자체가 내부에서 flatten화 시켜서 제거하는 것 so, [0, 1] 이렇게 인덱스 지정하면 0행 1열이 삭제되는 게 아니라 0번, 1번 인덱스가 지워지는 것

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [135]:
arr2 = np.delete(arr, [0,1]); arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [140]:
arr3 = np.delete(arr, 1, 0); arr3 # axis = 0은 행 삭제

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [141]:
arr4 = np.delete(arr, 1, 1); arr4 # axis = 1은 열 삭제

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [171]:
# 추가: insert(원데이터, index, 추가할 데이터, axis) -> 특정 위치(인덱스)에 추가하고 싶을 때
a = np.array([[1,1],
              [2,2],
              [3,3]]); a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [148]:
a1 = np.insert(a, 1, 100); a1 # axis를 지정하지 않으면 모든 요소 지정함에 유의 (flatten화 시키고 요소 추가) + 배열의 크기가 자동으로 커짐

array([  1, 100,   1,   2,   2,   3,   3])

In [158]:
a2 = np.insert(a, 1, 100, 0); a2 # axis = 0은 행 추가

array([[  1,   1],
       [100, 100],
       [  2,   2],
       [  3,   3]])

In [159]:
a3 = np.insert(a, 1, 99, 1); a3 #axis = 1은 열 추가

array([[ 1, 99,  1],
       [ 2, 99,  2],
       [ 3, 99,  3]])

In [169]:
# 서로 다른 값을 추가하려면 리스트 형식으로 지정
a4 = np.insert(a, 2, [2, 9], 0); a4 #axis = 0은 행 추가

array([[1, 1],
       [2, 2],
       [2, 9],
       [3, 3]])

In [170]:
# 서로 다른 값을 추가하려면 리스트 형식으로 지정
a5 = np.insert(a, 1, [99, 31, 28], 1); a5 #axis = 1은 열 추가

array([[ 1, 99,  1],
       [ 2, 31,  2],
       [ 3, 28,  3]])

In [186]:
# 추가: append(원데이터, 추가할 데이터, axis(축)) -> 연속해서(뒷 부분에) 추가(순서대로)하고 싶을 때
# np.append()는 rank가 같아야 결합이 가능
b = np.array([[1,2,3], 
              [4,5,6]]); b

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
b2 = np.append(b, 100); b2

array([  1,   2,   3,   4,   5,   6, 100])

In [188]:
b3 = np.append(b, [23,19,21], 0); b3 # 차원이 안 맞는다고 에러

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [189]:
b4 = np.append(b, [[34, 29,51]], 0); b4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [34, 29, 51]])

In [194]:
# cf) vsatck(): 행을 자동으로 추가해주는 함수
b5 = np.vstack((b, [7,8,9])); b5
# 왜 괄호 두 개??

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
# [실습]
# 1, 2, 3, 7
# 4, 5, 6, 8 
#b에 append로 추가하여 출력
b6 = np.append(b, [[7], [8]], 1); b6 # rank가 같아야 하니까 2행 1열로 추가할 데이터를 입력해줘야 함

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])