In [24]:
import numpy as np

In [25]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]); a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# 5,6,7,8(a의 2번째 행 요소값을 전부 출력)
b = a[1, :]; b ## 전제 가져오고 싶으면 : 쓰면 돼

array([5, 6, 7, 8])

In [27]:
# 2, 6, 10(a의 2번째 열 요소값을 전부 출력)
c = a[:,1]; c ## array([ 2,  6, 10])
# 왜 열 요소값을 출력했는데 행 형태로 출력되었는가?

# 열 형태로 뽑기 위해서는 어떻게 해야 하는가?
## 2번째 열 요소값을 전부 열 형태로 출력
d = a[:,1:2]; d # 그냥 1 하면 행 형태 1:2 하면 열 형태로 출력됨. (왜?)

array([[ 2],
       [ 6],
       [10]])

In [28]:
print(d.ndim, d.shape) ## 이거 왜 rank 가 2야?

2 (3, 1)


In [29]:
a = np.array([[1,2],[3,4],[5,6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# 1, 4, 5 요소 추출(행)
## 힌트: 리스트를 이용해서 원하는 행과 열을 각각 짝지을 수 있음

b = a[[0,1,2],[0,1,0]]; b #a의 (0,0), (1, 0), (2,0)으로 짝 지어서 빼내기

array([1, 4, 5])

In [46]:
'''
numpy 인덱싱: (기본) 행렬의 각 행에서 하나의 요소를 선택하거나 수정하는 기능
            : numpy의 인덱싱은 팬시 인덱싱(fancy indexing) 이라고소 함. 
            : 인덱스에 없는 번호로 하면 오류
            : 이를 이용해서 원본 배열과 다른 배열을 만들 때 유용 
'''

'\nnumpy 인덱싱: (기본) 행렬의 각 행에서 하나의 요소를 선택하거나 수정하는 기능\n            : numpy의 인덱싱은 팬시 인덱싱(fancy indexing) 이라고소 함. \n            인덱스에 없는 번호로 하면 오류\n'

In [59]:
a = np.array([1,2,3,4,5,6,7,8,9]); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
idx = np.array([0,0,0,0,1,1,1,1,2,2,2,2,6]); idx

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 6])

In [61]:
a[idx] ## numpy의 정수 인덱싱

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 7])

In [62]:
# a[2,4,5] -> 이렇게 하면 안돼
# a[[2,4,5]] -> 이렇게는 됨.

In [63]:
a = np.array([[1,2],[3,4],[5,6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
# [1,3,5] 추출 -> 열 형태로 추출
b = a[:,0:1]; b

array([[1],
       [3],
       [5]])

In [65]:
# 추출하고 싶은 열을 True 처리
# bool 인덱싱
c = a[:,[True, False]]; c

array([[1],
       [3],
       [5]])

## 배열 연산

- 배열 연산의 기본은 같은 위치에 있는 각각의 요소 별로 연산(동작)한다.
- numpy에서 제공하는 함수, 산술 연산자로 배열 연산이 가능
- 

In [66]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print('-' * 30)
print(y)

[[1 2]
 [3 4]]
------------------------------
[[5 6]
 [7 8]]


In [68]:
# 산술 연산이 가능하다.
x + y

array([[ 6,  8],
       [10, 12]])

In [69]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [70]:
x - y

array([[-4, -4],
       [-4, -4]])

In [71]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [72]:
x * y

array([[ 5, 12],
       [21, 32]])

In [73]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [75]:
x / y # 나눗셈 결과가 실수면 실수로 리턴

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [76]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [79]:
# 비교 연산도 가능 => 결과값을 True/False로 리턴
print(x)
print('-' * 30)
print(x == 2) ## Broadcasting

[[1 2]
 [3 4]]
------------------------------
[[False  True]
 [False False]]


In [81]:
print(y)
print('-'*30)
print(y > 6)

[[5 6]
 [7 8]]
------------------------------
[[False False]
 [ True  True]]


In [85]:
# [실습]
## x배열에 3보다 크고, y배열에 6보다 큰 값을 모두 만족하는 결과를 찾아보세요.
## 논리연산과 조합 가능
(x > 3) & (y > 6)

array([[False, False],
       [False,  True]])

In [86]:
4/3

1.3333333333333333

### 표준수학함수 - 기술 통계

In [89]:
x = np.array([18,5,10,2,3,11,-3,-5,9,-30,0,5,60,80,-4]); x

array([ 18,   5,  10,   2,   3,  11,  -3,  -5,   9, -30,   0,   5,  60,
        80,  -4])

In [91]:
len(x) # python 내장 함수

15

In [92]:
# 평균: 전체합 / 모수
np.mean(x)

10.733333333333333

In [93]:
# 분산 (variance): 데이터와 샘플 평균 간의 거리의 제곱의 평균
#                : 이 값이 작으면 데이터가 모여 있는 것, 이 값이 크면 데이터가 흩어져 있는 것
np.var(x)

660.7288888888888

In [94]:
# 표준편차 (Standar Deviaion): 분산의 제곱근 값
np.std(x)

25.70464722358369

In [96]:
# 최댓값(maximum), 최솟값(minmum), 중간값(median)
print(np.max(x))
print(np.min(x))
print(np.median(x)) # 데이터를 크기 대로 정렬 했을 때 가장 가운데 있는 수

80
-30
5.0


In [98]:
# 사분위수 (quertile): 데이터를 크기대로 정렬 1/4, 2/4, 3/4 위치에 있는 수 
#                                   (1사분위, 2사분위, 3사분위)

# numpy에서는 사분위수를 100으로 나눈 백분위수(percentile)를 사용

# numpy 사분위수 
print(np.percentile(x,0)) # 최솟값
print(np.percentile(x,25)) # 1사분위수
print(np.percentile(x,50)) # 2사분위수
print(np.percentile(x,75)) # 3사분위수
print(np.percentile(x,100)) # 최댓값
 


-30.0
-1.5
5.0
10.5
80.0


In [99]:
# 전체 합, 전체 곱
print(np.sum(x))
print(np.prod(x))

161
0


### 차원 축소 연산(dimention reduction)


In [104]:
x = np.array([1,10,100]); x

array([  1,  10, 100])

In [106]:
print(np.min(x), np.argmin(x))
print('-' * 30)
print(np.max(x), np.argmax(x))

1 0
------------------------------
100 2


In [107]:
# all: 배열의 모든 원소(요소)가 True인지 평가하는 메소드
np.all([True, False, True])

False

In [108]:
# any: 배열에서 1개 이상의 원소(요소)가 True인지 평가하는 메소드
np.any([False, False, True, True])

True